// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PRN232_PROJECT_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250628162058_update_v3")]
    partial class update_v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PRN232_PROJECT_API.Model.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "30b0f7fc-af44-4535-9884-f601ecf3c542",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "373589af-f723-4c4f-b706-742cf6453bb7",
                            Email = "user1@mail.com",
                            EmailConfirmed = true,
                            FullName = "User 1",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@MAIL.COM",
                            NormalizedUserName = "USER1@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIrGx7vhiI5W2VX/N54X4fbBKo/edmmvx9yRPUH9OJU+wrrBxdFd5sA3CTIIZP6c/Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "628a80f0-4f5b-4f01-9cf6-2a98855a05dc",
                            TwoFactorEnabled = false,
                            UserName = "user1@mail.com"
                        },
                        new
                        {
                            Id = "6e39dac9-6449-4526-9225-c3bed2642868",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "559c6e13-734b-48c9-bca7-39d99275860a",
                            Email = "user2@mail.com",
                            EmailConfirmed = true,
                            FullName = "User 2",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@MAIL.COM",
                            NormalizedUserName = "USER2@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAJgWe0iwybG48JR/vw26leKHWB/zsrvCQmAcrq92xx4wQECkAw48MrVP1w0OAWlIw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "45b9e2bd-6629-42ba-9dbf-faaf0c149c06",
                            TwoFactorEnabled = false,
                            UserName = "user2@mail.com"
                        },
                        new
                        {
                            Id = "30f6a7ea-7fbb-4868-8bdc-ef830fd9b524",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ca72f80f-d8fd-40d3-9380-97c9741e7b80",
                            Email = "user3@mail.com",
                            EmailConfirmed = true,
                            FullName = "User 3",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER3@MAIL.COM",
                            NormalizedUserName = "USER3@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECmYxLxaLboULkMMKJcUAVblsh/hTmNDlh8TuVPDgoHJSl6tcToaQIKy5eqx4vgRYg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1d30e0d7-7fb9-4c97-bb0c-b5c7a88bb9d4",
                            TwoFactorEnabled = false,
                            UserName = "user3@mail.com"
                        },
                        new
                        {
                            Id = "26ade076-eacf-4b38-b4e9-8974a12cd7b9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "635f7130-e269-4b0e-8809-825d1f15bd6f",
                            Email = "user4@mail.com",
                            EmailConfirmed = true,
                            FullName = "User 4",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER4@MAIL.COM",
                            NormalizedUserName = "USER4@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIDv8tYiZsXOcNMSSXydpFg7Rc+OhxcpYFiCTwIKg0NJMF8H+qlKZqypC5dS2LHM4g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bad8c9fa-c9cf-4df2-b26a-b5961327b468",
                            TwoFactorEnabled = false,
                            UserName = "user4@mail.com"
                        },
                        new
                        {
                            Id = "bd393cfd-81a8-42ea-9bf5-e1a08403193a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "98f76289-ee2b-4397-ad43-4d33beb3cb5c",
                            Email = "user5@mail.com",
                            EmailConfirmed = true,
                            FullName = "User 5",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER5@MAIL.COM",
                            NormalizedUserName = "USER5@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKvxuENk4I5+87biZKKB+kJp99dFlFfrNHTytziOvU9adKveKogQKF3QEfJ4vInK9w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f88eca44-c37c-4e4b-a231-1ba9307bf0f4",
                            TwoFactorEnabled = false,
                            UserName = "user5@mail.com"
                        },
                        new
                        {
                            Id = "8298ffaf-de2d-45f3-99d8-48b42bcbda1e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "18106f60-75fe-40ff-97ee-2bbe63beb925",
                            Email = "user6@mail.com",
                            EmailConfirmed = true,
                            FullName = "User 6",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER6@MAIL.COM",
                            NormalizedUserName = "USER6@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIFSQzZ7W0L73GfNSBSwDhEBYwEUHHAIVCD7BIsG4b4CHTzxM/RtDXI00WCc7hmNPg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5e8d5ac9-d467-457b-9f7b-4d63b39b855b",
                            TwoFactorEnabled = false,
                            UserName = "user6@mail.com"
                        },
                        new
                        {
                            Id = "f853b113-f84c-4052-8629-b77e2b55954b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0aa8deda-3387-4334-b698-e175bd0b566f",
                            Email = "user7@mail.com",
                            EmailConfirmed = true,
                            FullName = "User 7",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER7@MAIL.COM",
                            NormalizedUserName = "USER7@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHzJq3Ud+KLUpaoGKeK4QYWEYb1E6dyrIki53tvuh8e/yzfP+Yx397hX+3CktYCz+g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8e2751fb-1e3a-4c5a-ae97-183f11f90d5f",
                            TwoFactorEnabled = false,
                            UserName = "user7@mail.com"
                        },
                        new
                        {
                            Id = "3d954c97-a30d-4303-a33d-f979be10d117",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "233bf43d-460d-49e3-82c9-e2bcf82e6a38",
                            Email = "user8@mail.com",
                            EmailConfirmed = true,
                            FullName = "User 8",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER8@MAIL.COM",
                            NormalizedUserName = "USER8@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKTfBao9fw1FkZ44iM/uwPfceFWd1MWJZDjfaj5tfk5UZebDPbMBO0FivVzWm05xvQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "941e2aea-96fa-4bee-8aed-421b78dd8211",
                            TwoFactorEnabled = false,
                            UserName = "user8@mail.com"
                        },
                        new
                        {
                            Id = "b8f3a210-3810-429d-8df3-178c593cdcab",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bbfea742-fb78-4248-bc40-8d7916ff50c5",
                            Email = "user9@mail.com",
                            EmailConfirmed = true,
                            FullName = "User 9",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER9@MAIL.COM",
                            NormalizedUserName = "USER9@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBsqbjnxjECMxfVaZ0u7Bk3YujmHDQbwC60NkRH/XTT7gDhDXhOMqNyXFeFg+0u46w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "11b1bd03-9f5f-4b95-bf08-0f0be724b51e",
                            TwoFactorEnabled = false,
                            UserName = "user9@mail.com"
                        },
                        new
                        {
                            Id = "3897286d-b6c1-49f7-99de-d1539425c0ae",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "81b0abf4-5497-4c6a-aea2-7a6636920205",
                            Email = "user10@mail.com",
                            EmailConfirmed = true,
                            FullName = "User 10",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER10@MAIL.COM",
                            NormalizedUserName = "USER10@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMqJCXUFInKjBaAUKlHpCPydLh8Wm5/2dFDBYk7jV5SaceCd5B7nchUga0h2uGCr/g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b9f83d3b-6a97-4bec-8a8f-7bc840008ed4",
                            TwoFactorEnabled = false,
                            UserName = "user10@mail.com"
                        },
                        new
                        {
                            Id = "a2071d7a-5ca7-4616-918f-d84d1d9d4253",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6ede7b43-fa8d-4a31-8de9-9fd8495777d1",
                            Email = "user11@mail.com",
                            EmailConfirmed = true,
                            FullName = "User 11",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER11@MAIL.COM",
                            NormalizedUserName = "USER11@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJl5TuUbX9iYns9RPcWf6J+mu7tnmswQBOrtyWh1to75QgpDFn5/fOb5pYUr83qS7w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9f0a9001-c923-4773-bdde-ed4e9070d19c",
                            TwoFactorEnabled = false,
                            UserName = "user11@mail.com"
                        },
                        new
                        {
                            Id = "f44d764b-c05a-4dd7-b160-d85fb7d7b8e2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c00aca21-1a55-46c4-921c-3dfaa2769398",
                            Email = "user12@mail.com",
                            EmailConfirmed = true,
                            FullName = "User 12",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER12@MAIL.COM",
                            NormalizedUserName = "USER12@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAwshjgpUUKVzvBedUXZMwnZBfmw2EG2FP2s/dYaCQRjpkTO7Yj5xg4+NiWHJngt/w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "06d57047-d6be-4982-aed4-39efc172f330",
                            TwoFactorEnabled = false,
                            UserName = "user12@mail.com"
                        },
                        new
                        {
                            Id = "c592ca20-3d6f-46af-a810-221b7660630b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2fd65b3f-54eb-4666-9351-79b173559c47",
                            Email = "user13@mail.com",
                            EmailConfirmed = true,
                            FullName = "User 13",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER13@MAIL.COM",
                            NormalizedUserName = "USER13@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEP5U3v8VhspqDxabgp8vQQ9Y64EDLomCzSJnUEuaGnjAo/FOuH+46JX/0qyk2L9Xfw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5fc707be-ab21-4acf-b701-a57a6273c4a3",
                            TwoFactorEnabled = false,
                            UserName = "user13@mail.com"
                        },
                        new
                        {
                            Id = "504626e4-58f0-4857-b76c-432decc17ecf",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e4fa001f-63d2-4921-a3ac-85d6574d2ca2",
                            Email = "user14@mail.com",
                            EmailConfirmed = true,
                            FullName = "User 14",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER14@MAIL.COM",
                            NormalizedUserName = "USER14@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDii+PYsFKdwuZEwnHg8u83JwfBy0eszwkWw5z7rY/Tpea4gtWDbOlenAO/ivkK/iA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "067cef96-a376-4a85-821d-77f7ac24a8d2",
                            TwoFactorEnabled = false,
                            UserName = "user14@mail.com"
                        },
                        new
                        {
                            Id = "fc8ad219-5366-4c74-89be-9ed162aebdc5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3cfaa6a6-4895-4687-9149-a2d1503ccc4d",
                            Email = "user15@mail.com",
                            EmailConfirmed = true,
                            FullName = "User 15",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER15@MAIL.COM",
                            NormalizedUserName = "USER15@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ4s6Rpf9RUGS2cfFuUIqzPRC3xbRQGwAceizSPmKbTm7AABtXSF3Wjj5spfqA6+rQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "37538026-2533-4b6b-9567-8b420b538a26",
                            TwoFactorEnabled = false,
                            UserName = "user15@mail.com"
                        });
                });

            modelBuilder.Entity("PRN232_PROJECT_API.Model.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Content = "Sample content for article 1",
                            CreatedAt = new DateTime(2025, 6, 27, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(775),
                            ImageUrl = "none",
                            Source = "VN",
                            Status = 1,
                            Title = "Article Title 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Content = "Sample content for article 2",
                            CreatedAt = new DateTime(2025, 6, 26, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(792),
                            ImageUrl = "none",
                            Source = "VN",
                            Status = 1,
                            Title = "Article Title 2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            Content = "Sample content for article 3",
                            CreatedAt = new DateTime(2025, 6, 25, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(793),
                            ImageUrl = "none",
                            Source = "VN",
                            Status = 1,
                            Title = "Article Title 3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            Content = "Sample content for article 4",
                            CreatedAt = new DateTime(2025, 6, 24, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(794),
                            ImageUrl = "none",
                            Source = "VN",
                            Status = 1,
                            Title = "Article Title 4"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 6,
                            Content = "Sample content for article 5",
                            CreatedAt = new DateTime(2025, 6, 23, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(795),
                            ImageUrl = "none",
                            Source = "VN",
                            Status = 1,
                            Title = "Article Title 5"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 7,
                            Content = "Sample content for article 6",
                            CreatedAt = new DateTime(2025, 6, 22, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(796),
                            ImageUrl = "none",
                            Source = "VN",
                            Status = 1,
                            Title = "Article Title 6"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 8,
                            Content = "Sample content for article 7",
                            CreatedAt = new DateTime(2025, 6, 21, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(798),
                            ImageUrl = "none",
                            Source = "VN",
                            Status = 1,
                            Title = "Article Title 7"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 9,
                            Content = "Sample content for article 8",
                            CreatedAt = new DateTime(2025, 6, 20, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(799),
                            ImageUrl = "none",
                            Source = "VN",
                            Status = 1,
                            Title = "Article Title 8"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 10,
                            Content = "Sample content for article 9",
                            CreatedAt = new DateTime(2025, 6, 19, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(800),
                            ImageUrl = "none",
                            Source = "VN",
                            Status = 1,
                            Title = "Article Title 9"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 11,
                            Content = "Sample content for article 10",
                            CreatedAt = new DateTime(2025, 6, 18, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(801),
                            ImageUrl = "none",
                            Source = "VN",
                            Status = 1,
                            Title = "Article Title 10"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 12,
                            Content = "Sample content for article 11",
                            CreatedAt = new DateTime(2025, 6, 17, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(802),
                            ImageUrl = "none",
                            Source = "VN",
                            Status = 1,
                            Title = "Article Title 11"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 13,
                            Content = "Sample content for article 12",
                            CreatedAt = new DateTime(2025, 6, 16, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(804),
                            ImageUrl = "none",
                            Source = "VN",
                            Status = 1,
                            Title = "Article Title 12"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 14,
                            Content = "Sample content for article 13",
                            CreatedAt = new DateTime(2025, 6, 15, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(805),
                            ImageUrl = "none",
                            Source = "VN",
                            Status = 1,
                            Title = "Article Title 13"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 15,
                            Content = "Sample content for article 14",
                            CreatedAt = new DateTime(2025, 6, 14, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(807),
                            ImageUrl = "none",
                            Source = "VN",
                            Status = 1,
                            Title = "Article Title 14"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Content = "Sample content for article 15",
                            CreatedAt = new DateTime(2025, 6, 13, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(808),
                            ImageUrl = "none",
                            Source = "VN",
                            Status = 1,
                            Title = "Article Title 15"
                        });
                });

            modelBuilder.Entity("PRN232_PROJECT_API.Model.ArticleTag", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArticleTags");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            TagId = 2
                        },
                        new
                        {
                            ArticleId = 2,
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = 3,
                            TagId = 4
                        },
                        new
                        {
                            ArticleId = 4,
                            TagId = 5
                        },
                        new
                        {
                            ArticleId = 5,
                            TagId = 6
                        },
                        new
                        {
                            ArticleId = 6,
                            TagId = 7
                        },
                        new
                        {
                            ArticleId = 7,
                            TagId = 8
                        },
                        new
                        {
                            ArticleId = 8,
                            TagId = 9
                        },
                        new
                        {
                            ArticleId = 9,
                            TagId = 10
                        },
                        new
                        {
                            ArticleId = 10,
                            TagId = 11
                        },
                        new
                        {
                            ArticleId = 11,
                            TagId = 12
                        },
                        new
                        {
                            ArticleId = 12,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 13,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 14,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 15,
                            TagId = 1
                        });
                });

            modelBuilder.Entity("PRN232_PROJECT_API.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Category 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Category 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Category 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Category 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Category 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Category 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Category 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Category 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Category 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Category 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Category 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Category 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Category 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Category 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Category 15"
                        });
                });

            modelBuilder.Entity("PRN232_PROJECT_API.Model.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 2,
                            Content = "Comment 1 content.",
                            PostedAt = new DateTime(2025, 6, 28, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(1899),
                            UserId = "6e39dac9-6449-4526-9225-c3bed2642868"
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 3,
                            Content = "Comment 2 content.",
                            PostedAt = new DateTime(2025, 6, 28, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(1906),
                            UserId = "30f6a7ea-7fbb-4868-8bdc-ef830fd9b524"
                        },
                        new
                        {
                            Id = 3,
                            ArticleId = 4,
                            Content = "Comment 3 content.",
                            PostedAt = new DateTime(2025, 6, 28, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(1908),
                            UserId = "26ade076-eacf-4b38-b4e9-8974a12cd7b9"
                        },
                        new
                        {
                            Id = 4,
                            ArticleId = 5,
                            Content = "Comment 4 content.",
                            PostedAt = new DateTime(2025, 6, 28, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(1911),
                            UserId = "bd393cfd-81a8-42ea-9bf5-e1a08403193a"
                        },
                        new
                        {
                            Id = 5,
                            ArticleId = 6,
                            Content = "Comment 5 content.",
                            PostedAt = new DateTime(2025, 6, 28, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(1913),
                            UserId = "8298ffaf-de2d-45f3-99d8-48b42bcbda1e"
                        },
                        new
                        {
                            Id = 6,
                            ArticleId = 7,
                            Content = "Comment 6 content.",
                            PostedAt = new DateTime(2025, 6, 28, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(1919),
                            UserId = "f853b113-f84c-4052-8629-b77e2b55954b"
                        },
                        new
                        {
                            Id = 7,
                            ArticleId = 8,
                            Content = "Comment 7 content.",
                            PostedAt = new DateTime(2025, 6, 28, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(1921),
                            UserId = "3d954c97-a30d-4303-a33d-f979be10d117"
                        },
                        new
                        {
                            Id = 8,
                            ArticleId = 9,
                            Content = "Comment 8 content.",
                            PostedAt = new DateTime(2025, 6, 28, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(1923),
                            UserId = "b8f3a210-3810-429d-8df3-178c593cdcab"
                        },
                        new
                        {
                            Id = 9,
                            ArticleId = 10,
                            Content = "Comment 9 content.",
                            PostedAt = new DateTime(2025, 6, 28, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(1947),
                            UserId = "3897286d-b6c1-49f7-99de-d1539425c0ae"
                        },
                        new
                        {
                            Id = 10,
                            ArticleId = 11,
                            Content = "Comment 10 content.",
                            PostedAt = new DateTime(2025, 6, 28, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(1951),
                            UserId = "a2071d7a-5ca7-4616-918f-d84d1d9d4253"
                        },
                        new
                        {
                            Id = 11,
                            ArticleId = 12,
                            Content = "Comment 11 content.",
                            PostedAt = new DateTime(2025, 6, 28, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(1953),
                            UserId = "f44d764b-c05a-4dd7-b160-d85fb7d7b8e2"
                        },
                        new
                        {
                            Id = 12,
                            ArticleId = 13,
                            Content = "Comment 12 content.",
                            PostedAt = new DateTime(2025, 6, 28, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(1955),
                            UserId = "c592ca20-3d6f-46af-a810-221b7660630b"
                        },
                        new
                        {
                            Id = 13,
                            ArticleId = 14,
                            Content = "Comment 13 content.",
                            PostedAt = new DateTime(2025, 6, 28, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(1957),
                            UserId = "504626e4-58f0-4857-b76c-432decc17ecf"
                        },
                        new
                        {
                            Id = 14,
                            ArticleId = 15,
                            Content = "Comment 14 content.",
                            PostedAt = new DateTime(2025, 6, 28, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(1963),
                            UserId = "fc8ad219-5366-4c74-89be-9ed162aebdc5"
                        },
                        new
                        {
                            Id = 15,
                            ArticleId = 1,
                            Content = "Comment 15 content.",
                            PostedAt = new DateTime(2025, 6, 28, 16, 20, 58, 278, DateTimeKind.Utc).AddTicks(1986),
                            UserId = "30b0f7fc-af44-4535-9884-f601ecf3c542"
                        });
                });

            modelBuilder.Entity("PRN232_PROJECT_API.Model.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tag 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tag 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tag 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tag 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tag 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tag 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Tag 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Tag 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Tag 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tag 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Tag 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Tag 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Tag 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Tag 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Tag 15"
                        });
                });

            modelBuilder.Entity("PRN232_PROJECT_API.Model.UserArticle", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("RoleInArticle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "ArticleId");

                    b.HasIndex("ArticleId");

                    b.ToTable("UserArticles");

                    b.HasData(
                        new
                        {
                            UserId = "30b0f7fc-af44-4535-9884-f601ecf3c542",
                            ArticleId = 1,
                            RoleInArticle = "MainAuthor"
                        },
                        new
                        {
                            UserId = "6e39dac9-6449-4526-9225-c3bed2642868",
                            ArticleId = 2,
                            RoleInArticle = "MainAuthor"
                        },
                        new
                        {
                            UserId = "30f6a7ea-7fbb-4868-8bdc-ef830fd9b524",
                            ArticleId = 3,
                            RoleInArticle = "MainAuthor"
                        },
                        new
                        {
                            UserId = "26ade076-eacf-4b38-b4e9-8974a12cd7b9",
                            ArticleId = 4,
                            RoleInArticle = "MainAuthor"
                        },
                        new
                        {
                            UserId = "bd393cfd-81a8-42ea-9bf5-e1a08403193a",
                            ArticleId = 5,
                            RoleInArticle = "MainAuthor"
                        },
                        new
                        {
                            UserId = "8298ffaf-de2d-45f3-99d8-48b42bcbda1e",
                            ArticleId = 6,
                            RoleInArticle = "MainAuthor"
                        },
                        new
                        {
                            UserId = "f853b113-f84c-4052-8629-b77e2b55954b",
                            ArticleId = 7,
                            RoleInArticle = "MainAuthor"
                        },
                        new
                        {
                            UserId = "3d954c97-a30d-4303-a33d-f979be10d117",
                            ArticleId = 8,
                            RoleInArticle = "MainAuthor"
                        },
                        new
                        {
                            UserId = "b8f3a210-3810-429d-8df3-178c593cdcab",
                            ArticleId = 9,
                            RoleInArticle = "MainAuthor"
                        },
                        new
                        {
                            UserId = "3897286d-b6c1-49f7-99de-d1539425c0ae",
                            ArticleId = 10,
                            RoleInArticle = "MainAuthor"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PRN232_PROJECT_API.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PRN232_PROJECT_API.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN232_PROJECT_API.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PRN232_PROJECT_API.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PRN232_PROJECT_API.Model.Article", b =>
                {
                    b.HasOne("PRN232_PROJECT_API.Model.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PRN232_PROJECT_API.Model.ArticleTag", b =>
                {
                    b.HasOne("PRN232_PROJECT_API.Model.Article", "Article")
                        .WithMany("ArticleTags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN232_PROJECT_API.Model.Tag", "Tag")
                        .WithMany("ArticleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PRN232_PROJECT_API.Model.Comment", b =>
                {
                    b.HasOne("PRN232_PROJECT_API.Model.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN232_PROJECT_API.Model.ApplicationUser", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN232_PROJECT_API.Model.UserArticle", b =>
                {
                    b.HasOne("PRN232_PROJECT_API.Model.Article", "Article")
                        .WithMany("UserArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN232_PROJECT_API.Model.ApplicationUser", "User")
                        .WithMany("UserArticles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN232_PROJECT_API.Model.ApplicationUser", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("UserArticles");
                });

            modelBuilder.Entity("PRN232_PROJECT_API.Model.Article", b =>
                {
                    b.Navigation("ArticleTags");

                    b.Navigation("Comments");

                    b.Navigation("UserArticles");
                });

            modelBuilder.Entity("PRN232_PROJECT_API.Model.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("PRN232_PROJECT_API.Model.Tag", b =>
                {
                    b.Navigation("ArticleTags");
                });
#pragma warning restore 612, 618
        }
    }
}
